name: Maskoding Decode
title: Maskoding Decode
description: JavaScript Deobfuscator and Unpacker
version: 1.6.2
author: maskoding
author_email: abdiusu@gmail.com
url: https://maskodingku.github.io
baseurl: /decode-maskoding
repository: maskodingku/decode-maskoding
license: MIT

theme: jekyll-theme-hacker
show_downloads: false
google_analytics: 
sass:
  style: compressed

exclude: ['Gemfile', 'Gemfile.lock', 'node_modules', 'package.json', 'package-lock.json']
incremental: false
